services:
  node:
    build:
      context: .
      dockerfile: ./containers/node/Dockerfile
    working_dir: /home/node/app
    volumes:
      - ./volumes/app:/home/node/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
      - "6001:6001"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
    environment:
      - NODE_ENV=devGlobal
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./tmp/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./containers/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node
